replicas:
  _default: 1
  dev: 1

selector : dev

name:
  app: warehouse-helm

service:
  nameApp: warehouse-helm-service
  portName: port-warehouse
  type: NodePort
  port: 80
  targetPort: 8001

kafka:
  portName: port-delivery-kafka
  type: NodePort
  port: 9092
  targetPort: 9092
  bootstrap: kafka:9092

image:
  repository: bobah165/warehouse
  tag: v14

ingress:
  enabled: false
  name: "warehouse-service-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path:
    warehouse: /api/warehouse

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres


app:
  db:
    password:
      _default: cG9zdGdyZXM=
    username:
      _default: cG9zdGdyZXM=

