spring:
  application:
    name: warehouse-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: "order-2"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        request:
          timeout:
            ms: ${KAFKA_CONSUMER_TIMEOUT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    properties:
      heartbeat:
        interval:
          ms: ${KAFKA_HEARTBEAT}
      session:
        timeout:
          ms: ${KAFKA_SESSION}

server:
  port: 8001
  shutdown: graceful

topic:
  consumer:
    pay: send-pay-to-warehouse-event
    delivery: send-delivery-to-warehouse-event
  producer:
    pay: send-warehouse-to-pay-event
    delivery: send-warehouse-to-delivery-event
  saga:
    delivery: send-delivery-saga-event
    warehouse: send-warehouse-saga-event
