---
apiVersion: v1
kind: Secret
metadata:
  name: db-{{ .Values.name.app }}
type: Opaque
data:
  db_password: {{  .Values.app.db.password._default }}
  db_username: {{  .Values.app.db.username._default }}
