apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nameApp }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.selector }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.portName }}
      targetPort: {{ .Values.service.targetPort }}
